version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  TERM: dumb
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    # Currently Java8 is disabled due to a bug
    # - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - npm -g install npm@2
  - set PATH=%APPDATA%\npm;%JAVA_HOME%\bin;%PATH%
  - echo %PATH%
  - gradlew.bat clean npmInstall --stacktrace
  - set JAVA_OPTS=-XX:MaxPermSize=1024m -Xmx1512m
build_script:
  - gradlew.bat -u -i build
test_script:
  - gradlew.bat -u -i -S testUnit
cache:
  - .gradle
  - C:\Users\appveyor\.gradle
on_failure:
  - echo It seems something went kaput
